### ISSUE TITLE
website not save

### ISSUE THREAD

**Issue by dobbelos** [benhuson/password-protected#131]
I installed the plugin on my website, but when the loginscreen opens i get the following message in the adres bar: Website nicht sicher (
![IMG_5967](https://user-images.githubusercontent.com/49274010/55549941-570df280-56d7-11e9-836a-849d5294d2fd.jpg)
website not save) I am from Switzerland, so i use the german WP version.
How to get rid of this error message ?
Does`nt look very professional on my site :-(
Hope someone can help me out here.

**Comment by benhuson** [comment]
Hi

I think that may be the “Website not secure” message that your Browser shows if the website is not protected by a secure certificate (ie. using https)

You fix it you would need to purchase/install a secure certicate for your hosting and make sure your website url is configured to be https instead of http - there are WordPress SSL plugins that can help with this.

Kind regards

Ben

**Comment by bernie2505** [comment]
Dear Ben,
first of all, thanks  a lot for this splendid piece of software! Alas, though I have installed and activated  it on my webpage which is protected by a working secure certificate (https://...) the link is presented as "not secure"! However, after having entered the password a secure link to my webpage is shown. where do I go wrong? Any idea? Thanks  a lot for you support and again this execellent plugin!
Cheers from Bernie
