### ISSUE TITLE
Redirecting to Homepage & Cookie Problem

### ISSUE THREAD

**Issue by michaelfricanoii** [benhuson/password-protected#159]
My users have started experiencing the issue of being redirected to the homepage after attempting to open the most recent blog post. Clearing the browser cache/cookies/history resolves this issue and they have to re-enter the password. Also, deactivating the plugin resolves the problem. How can this be fixed so that users don't run in to this problem at all?

**Comment by luhvleedesignco** [comment]
I am having this same issue.

**Comment by rxnlabs** [comment]
@michaelfricanoii @luhvleedesignco This is due to how the plugin handles the redirect that takes place when you are not logged in. Even though the plugin does do a 302 redirect to the login page, the 302 redirect can get cached by the browser since a 302 redirect does not mean that the browser won't cache the page.

A workaround fix is to add this code to your theme's `functions.php` file. 

```php
/**
Force the password protect redirect to send a No Cache header when the redirect takes place.

This prevents the user's browser from caching the redirect and making the browser think that redirect page is the original page that the user wanted to go to.
*/
function password_protect_fix( $location, $status ) {
	if ( is_admin() ) {
		return $location;
	}

	$query_args = wp_parse_url( $location, PHP_URL_QUERY );

	if ( ! empty( $query_args ) && false !== strpos( $query_args, 'password-protected' ) ) {
		nocache_headers();
	}

	return $location;
}
add_filter( 'wp_redirect', 'password_protect_fix', 10, 2 );
```

**Comment by benhuson** [comment]
PR merged. Will be in next release.
