### ISSUE TITLE
Problem with Better WP Security

### ISSUE THREAD

**Issue by cfarence** [benhuson/password-protected#24]
I love this plugin, it looks very nice using the default WordPress login page. Though I did find one problem. I have Better WP security installed with hide mode enabled. This hides and protects my wp-admin and wp-login.php files and directories. If your not logged into WordPress when trying to access /wp-admin you will get a 404 error. 

This has been causing problems because the password protected plugin is trying to use two style sheets that's located in wp-admin. wp-admin/css/wp-admin.min.css?ver=3.5.1 and colors-fresh.min.css?ver=3.5.1.

Here is what it looks like with out the style sheets loaded
https://f.cloud.github.com/assets/3825621/630041/de3c587c-d187-11e2-801f-8347bb718d53.png
.

**Comment by benhuson** [comment]
The Password Protected login page is based on the code from the main WordPress login page (which is why they look the same by default.

For the main WordPress login you have to enqueue stylesheets slightly differently using 'login_enqueue_scripts' - see https://codex.wordpress.org/Plugin_API/Action_Reference/login_enqueue_scripts

That should work for Password Protected too but I have not tested this yet.

The next version of the plugin (version 2.0) will check for a 'password-protected-login.css' in your theme folder and load that automatically if it exists. You'll be able to use a 'password_protected_stylesheet_file' filter if you want to load a different filename or a stylesheet in a subfolder of your theme.
