### ISSUE TITLE
Password box appears on homepage

### ISSUE THREAD

**Issue by mikez2016** [benhuson/password-protected#72]
After installing Password Protected, a password box is now appearing on my main page, after I log in.  I deactivated the plugin and it still appears.  How do I remove this?  I am scheduled to go live with my site this week!  THank you very much in advance!

Above the password filed, it says "This content is password protected. To view it please enter your password below:"  Screen shot attached.

![screen shot 2016-04-05 at 5 07 33 pm](https://cloud.githubusercontent.com/assets/18296830/14301982/f328723e-fb50-11e5-8ed4-2ec8809b2486.png)

**Comment by benhuson** [comment]
If you have disabled the plugin and you are still viewing the login, it is likely your web server has server side page caching which is not compatible with the Password Protected plugin - so the server has cached and is displaying a pre-rendered version of the page.

If your WordPress install has any caching plugins, try flushing the cache.

Otherwise your hosting may have a control panel that allows you to flush the server cache.
